#!/bin/bash

#0* 144hz
#1* Acer

MAIN_MONITOR="1"
ALT_MONITOR=""
#$(expr $(bspc query -M | wc -l) - 1)
WS10_ALT_MONITOR=$(expr \( $ALT_MONITOR + 1 \) \* 10)

bspc rule -a "TeamSpeak 3"          desktop="^${ALT_MONITOR}1"
bspc rule -a "Firefox:*"            desktop="^${MAIN_MONITOR}1"
bspc rule -a "Spotify:*"            desktop="^${ALT_MONITOR}2"
bspc rule -a "Hexchat:*"            desktop="^${ALT_MONITOR}2"
bspc rule -a "Astroid:*"            desktop="^${ALT_MONITOR}3"
bspc rule -a "Steam:*"              desktop="^${MAIN_MONITOR}5"
bspc rule -a "Galculator:*"         state=floating
bspc rule -a "Zenity:*"             state=floating
bspc rule -a "KeePass2:*"           desktop="^${ALT_MONITOR}3"
bspc rule -a "Corebird:*"           desktop="^${ALT_MONITOR}2"
bspc rule -a "Qemu-system-x86_64:*" state=floating
bspc rule -a "discord:*"            desktop="^${ALT_MONITOR}1"
bspc rule -a "Deluge:*"             desktop="^${ALT_MONITOR}9"
bspc rule -a "Slack:*"              desktop="^${WS10_ALT_MONITOR}"
#bspc rule -a "csgo_linux64:*" state=fullscreen desktop="^${MAIN_MONITOR}5"
#bspc rule -a "ibus-ui-gtk3:*" state=floating

wildbar &
trayer --edge top --align left --widthtype request --heighttype pixel --height 14 --transparent true --alpha 0 --tint 0x232C31 --distance 255 --distancefrom left --monitor primary &
/usr/lib/xfce-polkit/xfce-polkit &
systemctl --user start emacs.service
#firewall-applet &
firefox &
corebird &
#thunderbird &
astroid &
dropboxd &
megasync &
keepass &
steam &
spotify &
teamspeak3 &
hexchat &
#deluge &
slack &
discord &
xscreensaver -nosplash &
echo -e 'power on\nscan on\ndefault-agent\nquit' | bluetoothctl
#compton --config ~/.compton.conf --paint-on-overlay --backend glx --unredir-if-possible -b &
